-- ============================================================================
-- Day 07: Cohort Analysis Model for Carol's Pousada
-- ============================================================================
-- Business Purpose:
--   Analyze guest behavior by cohort (month of first booking) to understand:
--   - Which acquisition periods bring the most valuable guests
--   - How different cohorts behave over time
--   - Seasonal patterns in guest quality and retention
--
-- Stakeholder: Carol (Pousada Owner)
-- Use Case: Optimize marketing spend by focusing on high-value cohort months
-- ============================================================================

-- ============================================================================
-- STEP 1: Identify First Booking per Guest (Cohort Assignment)
-- ============================================================================
-- This CTE assigns each guest to a cohort based on their first booking date.
-- The cohort is the YYYY-MM of their first interaction with the pousada.

DROP VIEW IF EXISTS day07_guest_cohorts;
CREATE VIEW day07_guest_cohorts AS

WITH day07_first_booking AS (
    SELECT
        guest_id,
        MIN(booking_date) as first_booking_date,
        MIN(check_in_date) as first_stay_date,
        -- Cohort is defined as YYYY-MM of first booking
        STRFTIME('%Y-%m', MIN(booking_date)) as cohort_month,
        -- Also useful: year and month separately for aggregations
        CAST(STRFTIME('%Y', MIN(booking_date)) AS INTEGER) as cohort_year,
        CAST(STRFTIME('%m', MIN(booking_date)) AS INTEGER) as cohort_month_num
    FROM day07_bookings
    WHERE status != 'Cancelled'  -- Only consider completed bookings for cohorts
    GROUP BY guest_id
),

-- ============================================================================
-- STEP 2: Enrich with Guest Details
-- ============================================================================
-- Join back to guest table to get demographic information

day07_cohort_guests AS (
    SELECT
        fb.guest_id,
        fb.first_booking_date,
        fb.first_stay_date,
        fb.cohort_month,
        fb.cohort_year,
        fb.cohort_month_num,
        g.first_name,
        g.last_name,
        g.email,
        g.country,
        g.guest_type,
        g.vip_status,
        -- Calculate days between registration and first booking
        JULIANDAY(fb.first_booking_date) - JULIANDAY(g.registration_date) as days_to_first_booking
    FROM day07_first_booking fb
    JOIN day07_guests g ON fb.guest_id = g.guest_id
),

-- ============================================================================
-- STEP 3: Calculate Cohort Metrics
-- ============================================================================
-- Aggregate metrics at the cohort level to understand cohort characteristics

day07_cohort_summary AS (
    SELECT
        cohort_month,
        cohort_year,
        cohort_month_num,

        -- Size and composition
        COUNT(DISTINCT guest_id) as cohort_size,
        COUNT(DISTINCT CASE WHEN guest_type = 'Couple' THEN guest_id END) as couples_count,
        COUNT(DISTINCT CASE WHEN guest_type = 'Family' THEN guest_id END) as families_count,
        COUNT(DISTINCT CASE WHEN guest_type = 'Individual' THEN guest_id END) as individuals_count,
        COUNT(DISTINCT CASE WHEN guest_type = 'Business' THEN guest_id END) as business_count,

        -- Demographics
        COUNT(DISTINCT CASE WHEN country = 'Brazil' THEN guest_id END) as brazilian_count,
        COUNT(DISTINCT CASE WHEN country != 'Brazil' THEN guest_id END) as international_count,
        COUNT(DISTINCT CASE WHEN vip_status = 1 THEN guest_id END) as vip_count,

        -- Timing metrics
        ROUND(AVG(days_to_first_booking), 1) as avg_days_reg_to_booking,
        MIN(first_booking_date) as cohort_start_date,
        MAX(first_booking_date) as cohort_end_date

    FROM day07_cohort_guests
    GROUP BY cohort_month, cohort_year, cohort_month_num
),

-- ============================================================================
-- STEP 4: Add Booking Activity per Cohort
-- ============================================================================
-- Calculate total bookings and revenue generated by each cohort

day07_cohort_activity AS (
    SELECT
        cg.cohort_month,

        -- Booking volume
        COUNT(DISTINCT b.booking_id) as total_bookings,
        COUNT(DISTINCT CASE WHEN b.status = 'Cancelled' THEN b.booking_id END) as cancelled_bookings,
        COUNT(DISTINCT CASE WHEN b.status != 'Cancelled' THEN b.booking_id END) as completed_bookings,

        -- Revenue metrics
        ROUND(SUM(CASE WHEN b.status != 'Cancelled' THEN b.total_price_brl ELSE 0 END), 2) as total_revenue_brl,
        ROUND(AVG(CASE WHEN b.status != 'Cancelled' THEN b.total_price_brl END), 2) as avg_booking_value_brl,

        -- Booking behavior
        ROUND(AVG(JULIANDAY(b.check_in_date) - JULIANDAY(b.booking_date)), 1) as avg_lead_time_days,

        -- Room preferences
        COUNT(DISTINCT CASE WHEN b.room_type = 'Suite' THEN b.booking_id END) as suite_bookings,
        COUNT(DISTINCT CASE WHEN b.room_type = 'Deluxe' THEN b.booking_id END) as deluxe_bookings,
        COUNT(DISTINCT CASE WHEN b.room_type = 'Standard' THEN b.booking_id END) as standard_bookings,

        -- Booking sources
        COUNT(DISTINCT CASE WHEN b.booking_source = 'Direct Website' THEN b.booking_id END) as direct_bookings,
        COUNT(DISTINCT CASE WHEN b.booking_source = 'Booking.com' THEN b.booking_id END) as booking_com,
        COUNT(DISTINCT CASE WHEN b.booking_source = 'Airbnb' THEN b.booking_id END) as airbnb_bookings

    FROM day07_cohort_guests cg
    JOIN day07_bookings b ON cg.guest_id = b.guest_id
    GROUP BY cg.cohort_month
),

-- ============================================================================
-- STEP 5: Add Stay Experience Metrics per Cohort
-- ============================================================================
-- Include satisfaction and spend metrics from actual stays

day07_cohort_experience AS (
    SELECT
        cg.cohort_month,

        -- Experience metrics
        COUNT(DISTINCT s.stay_id) as total_stays,
        ROUND(AVG(s.guest_rating), 2) as avg_guest_rating,
        COUNT(DISTINCT CASE WHEN s.guest_rating >= 5 THEN s.stay_id END) as five_star_stays,
        COUNT(DISTINCT CASE WHEN s.guest_rating <= 3 THEN s.stay_id END) as poor_rating_stays,

        -- Additional spend
        ROUND(SUM(s.extras_spent_brl), 2) as total_extras_brl,
        ROUND(AVG(s.extras_spent_brl), 2) as avg_extras_per_stay_brl,

        -- Review engagement
        COUNT(DISTINCT CASE WHEN s.review_text IS NOT NULL THEN s.stay_id END) as reviews_submitted,

        -- Repeat behavior indicator
        COUNT(DISTINCT CASE WHEN s.repeat_guest = 1 THEN s.stay_id END) as repeat_stay_count

    FROM day07_cohort_guests cg
    JOIN day07_stays s ON cg.guest_id = s.guest_id
    GROUP BY cg.cohort_month
)

-- ============================================================================
-- FINAL OUTPUT: Complete Cohort Analysis View
-- ============================================================================
-- Combine all metrics into a comprehensive cohort analysis table

SELECT
    cs.cohort_month,
    cs.cohort_year,
    cs.cohort_month_num,
    cs.cohort_start_date,
    cs.cohort_end_date,

    -- === COHORT SIZE & COMPOSITION ===
    cs.cohort_size,
    ROUND(100.0 * cs.couples_count / cs.cohort_size, 1) as couples_pct,
    ROUND(100.0 * cs.families_count / cs.cohort_size, 1) as families_pct,
    ROUND(100.0 * cs.individuals_count / cs.cohort_size, 1) as individuals_pct,
    ROUND(100.0 * cs.business_count / cs.cohort_size, 1) as business_pct,

    -- === DEMOGRAPHICS ===
    cs.brazilian_count,
    cs.international_count,
    ROUND(100.0 * cs.international_count / cs.cohort_size, 1) as international_pct,
    cs.vip_count,
    ROUND(100.0 * cs.vip_count / cs.cohort_size, 1) as vip_pct,

    -- === BOOKING BEHAVIOR ===
    ca.total_bookings,
    ca.completed_bookings,
    ca.cancelled_bookings,
    ROUND(100.0 * ca.cancelled_bookings / ca.total_bookings, 1) as cancellation_rate_pct,
    ROUND(1.0 * ca.total_bookings / cs.cohort_size, 2) as bookings_per_guest,
    ca.avg_lead_time_days,
    cs.avg_days_reg_to_booking,

    -- === REVENUE METRICS ===
    ca.total_revenue_brl,
    ca.avg_booking_value_brl,
    ROUND(ca.total_revenue_brl / cs.cohort_size, 2) as revenue_per_guest_brl,

    -- === ROOM PREFERENCES ===
    ROUND(100.0 * ca.suite_bookings / ca.total_bookings, 1) as suite_pct,
    ROUND(100.0 * ca.deluxe_bookings / ca.total_bookings, 1) as deluxe_pct,
    ROUND(100.0 * ca.standard_bookings / ca.total_bookings, 1) as standard_pct,

    -- === BOOKING CHANNELS ===
    ROUND(100.0 * ca.direct_bookings / ca.total_bookings, 1) as direct_channel_pct,
    ROUND(100.0 * ca.booking_com / ca.total_bookings, 1) as booking_com_pct,
    ROUND(100.0 * ca.airbnb_bookings / ca.total_bookings, 1) as airbnb_pct,

    -- === EXPERIENCE & SATISFACTION ===
    ce.total_stays,
    ce.avg_guest_rating,
    ROUND(100.0 * ce.five_star_stays / ce.total_stays, 1) as five_star_pct,
    ROUND(100.0 * ce.poor_rating_stays / ce.total_stays, 1) as poor_rating_pct,
    ROUND(100.0 * ce.reviews_submitted / ce.total_stays, 1) as review_rate_pct,

    -- === ADDITIONAL SPEND ===
    ce.total_extras_brl,
    ce.avg_extras_per_stay_brl,
    ROUND(ce.total_extras_brl / cs.cohort_size, 2) as extras_per_guest_brl,

    -- === TOTAL VALUE ===
    ROUND(ca.total_revenue_brl + ce.total_extras_brl, 2) as total_cohort_value_brl,
    ROUND((ca.total_revenue_brl + ce.total_extras_brl) / cs.cohort_size, 2) as value_per_guest_brl,

    -- === RETENTION INDICATOR ===
    ce.repeat_stay_count,
    ROUND(100.0 * ce.repeat_stay_count / ce.total_stays, 1) as repeat_guest_pct,

    -- === QUALITY SCORE (Composite) ===
    -- Custom metric: combines multiple factors into a single cohort quality score (0-100)
    ROUND(
        (ce.avg_guest_rating / 5.0 * 30) +  -- 30% weight on satisfaction
        (MIN(1.0 * ca.total_bookings / cs.cohort_size / 3.0, 1.0) * 25) +  -- 25% weight on repeat bookings (capped at 3x)
        (MIN(ce.avg_extras_per_stay_brl / 200.0, 1.0) * 20) +  -- 20% weight on extras spend (capped at R$200)
        ((1 - ca.cancelled_bookings / ca.total_bookings) * 15) +  -- 15% weight on low cancellations
        (ca.direct_bookings / ca.total_bookings * 10)  -- 10% weight on direct bookings (higher margin)
    , 1) as cohort_quality_score,

    -- === SEASONALITY INDICATOR ===
    CASE
        WHEN cs.cohort_month_num IN (6, 7, 8) THEN 'High (Winter)'
        WHEN cs.cohort_month_num IN (12, 1) THEN 'High (Summer)'
        ELSE 'Low'
    END as season_category

FROM day07_cohort_summary cs
LEFT JOIN day07_cohort_activity ca ON cs.cohort_month = ca.cohort_month
LEFT JOIN day07_cohort_experience ce ON cs.cohort_month = ce.cohort_month
ORDER BY cs.cohort_year, cs.cohort_month_num;

-- ============================================================================
-- BUSINESS INSIGHTS & USAGE
-- ============================================================================
--
-- This view enables Carol to answer questions like:
--
-- 1. "Which months bring the highest quality guests?"
--    → Look at cohort_quality_score and value_per_guest_brl
--
-- 2. "Do winter or summer cohorts spend more?"
--    → Compare avg_booking_value_brl by season_category
--
-- 3. "Which cohorts have the best retention?"
--    → Check bookings_per_guest and repeat_guest_pct
--
-- 4. "Should we invest more in direct marketing vs. OTAs?"
--    → Compare direct_channel_pct with cohort_quality_score
--
-- 5. "Do international guests behave differently?"
--    → Filter by international_pct and compare metrics
--
-- 6. "Which cohorts should we re-target for campaigns?"
--    → High cohort_quality_score + low repeat_guest_pct = opportunity
--
-- Sample Query:
-- SELECT cohort_month, cohort_size, value_per_guest_brl, cohort_quality_score
-- FROM day07_guest_cohorts
-- WHERE season_category = 'High (Winter)'
-- ORDER BY cohort_quality_score DESC;
-- ============================================================================
