day09_property_ops:
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: 'day09_property_operations'
      schema: 'main'
      schemas_and_paths:
        main: './data/day09_property_operations.db'
      schema_directory: './data'
  target: dev
